# These are the same as the defaults in the service file
# Change them to your preference and then call
# `systemctl --user daemon-reload && systemctl --user restart nightynight-off.timer`

OnCalendar=Mon..Fri 07:00:00
OnCalendar=Sat,Sun 09:00:00
