# These are the same as the defaults in the service file
# Change to your preference and then call
# `systemctl --user daemon-reload && systemctl --user restart nightynight-on.timer`

[Timer]
OnCalendar=
OnCalendar=*-*-* 20:30:00
