#!/bin/bash
## TODO: store states of dark/light mode, nightlight, autobrightness, and feedback profile

MODE="${1:-auto}"
NOW="$(date +%s)"

CONFIG_DIR="$HOME/.config/nightynight"
mkdir -p "$CONFIG_DIR"
CONFIG_FILE="$CONFIG_DIR/nightynight.conf"

## define defaults
# nightlight 0=don't enable, 1=enable
DEF_NLT_ON=1
# dark mode 0=don't enable, 1=enable
DEF_DRK_ON=1
# autobrightness 0=don't enable, 1=enable
DEF_BRT_ON=1
# feedback profile 0=don't change, 1=silent, 2=quiet
DEF_FB_LEV=1

if [ ! -f "$CONFIG_FILE" ]; then
  cat <<EOF > "${CONFIG_FILE}"
# nightlight 0=don't enable, 1=enable
NLT_ON=$DEF_NLT_ON
# dark mode 0=don't enable, 1=enable
DRK_ON=$DEF_DRK_ON
# autobrightness 0=don't enable, 1=enable
BRT_ON=$DEF_BRT_ON
# feedback profile 0=don't change, 1=silent, 2=quiet
FB_LEV=$DEF_FB_LEV
EOF
fi

source "$CONFIG_FILE" 2>/dev/null
#Fallbacks
: "${NLT_ON:=$DEF_NLT_ON}"
: "${DRK_ON:=$DEF_DRK_ON}"
: "${BRT_ON:=$DEF_BRT_ON}"
: "${FB_LEV:=$DEF_FB_LEV}"

STATE_FILE="$CONFIG_DIR/restore.conf"
NLT_STATE=0
BRT_STATE=0
DRK_STATE=0
FBK_STATE=0

if [ "$MODE" == "auto" ]; then
  NEXTON=$(date -d "$(systemctl --user list-timers --all --no-legend | grep nightynight-on.timer | sed 's/[- ]*//' | awk '{print $2, $3}')" +%s)
  NEXTOFF=$(date -d "$(systemctl --user list-timers --all --no-legend | grep nightynight-off.timer | sed 's/[- ]*//' | awk '{print $2, $3}')" +%s)
  [[ "$NOW" -lt "$NEXTOFF" ]] && [[ "$NEXTON" -le "$NOW" || "$NEXTON" -gt "$NEXTOFF" ]] && MODE="on"
  [[ "$NOW" -lt "$NEXTON" ]] && [[ "$NEXTOFF" -le "$NOW" || "$NEXTOFF" -gt "$NEXTON" ]] && MODE="off"
fi

if [ "$MODE" == "on" ]; then
  echo "Setting up Nighty-night mode."
  [ -f "$STATE_FILE" ] && mv "$STATE_FILE" "${STATE_FILE}.bak" && echo "Previous restoration settings were found and moved to ${STATE_FILE}.bak"
  [[ $NLT_ON -eq 1 ]] && NLT_STATE="$(gsettings get org.gnome.settings-daemon.plugins.color night-light-enabled)" && echo "  Recording current Night Light state ($NLT_STATE)" && echo "  Enabling Night Light" && gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true
  [[ $BRT_ON -eq 1 ]] && BRT_STATE="$(gsettings get org.gnome.settings-daemon.plugins.power ambient-enabled)" && echo "  Recording current Ambient Light Sensor state ($BRT_STATE)" && echo "  Enabling Ambient Light Sensor" && gsettings set org.gnome.settings-daemon.plugins.power ambient-enabled true
  [[ $DRK_ON -eq 1 ]] && DRK_STATE="$(gsettings get org.gnome.desktop.interface color-scheme)" && echo "  Recording current theme style ($DRK_STATE)" && echo "  Switching theme to Dark Style" && gsettings set org.gnome.desktop.interface color-scheme prefer-dark
  [[ $FB_LEV -gt 0 ]] && FBK_STATE="$(gsettings get org.sigxcpu.feedbackd profile)" && echo "  Recording current Feedback Profile ($FBK_STATE)"
  if [[ $FB_LEV -eq 1 ]]; then
    echo "  Setting Feedback Profile to Silent" && gsettings set org.sigxcpu.feedbackd profile silent
  elif [[ $FB_LEV -eq 2 ]]; then
    echo "  Setting Feedback Profile to Quiet" && gsettings set org.sigxcpu.feedbackd profile quiet
  fi
  cat <<EOF > "${STATE_FILE}"
    NLT_STATE=$NLT_STATE
    BRT_STATE=$BRT_STATE
    DRK_STATE=$DRK_STATE
    FBK_STATE=$FBK_STATE
EOF
elif [ "$MODE" == "off" ]; then
  [ -f "$STATE_FILE" ] && source "$STATE_FILE" 2>/dev/null && rm "$STATE_FILE"
  echo "Turning off Nighty-night mode."
  [[ $NLT_ON -ne 0 ]] && [[ $NLT_STATE != 0 ]] && echo "  Restoring Night Light state ($NLT_STATE)" && gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled "$NLT_STATE"
  [[ $BRT_ON -ne 0 ]] && [[ $BRT_STATE != 0 ]] && echo "  Restoring Ambient Light Sensor state ($BRT_STATE)" && gsettings set org.gnome.settings-daemon.plugins.power ambient-enabled "$BRT_STATE"
  [[ $DRK_ON -ne 0 ]] && [[ $DRK_STATE != 0 ]] && echo "  Restoring theme style ($DRK_STATE)" && gsettings set org.gnome.desktop.interface color-scheme "$DRK_STATE"
  [[ $FB_LEV -ne 0 ]] && [[ $FBK_STATE != 0 ]] && echo "  Restoring Feedback Profile ($FBK_STATE)" && gsettings set org.sigxcpu.feedbackd profile "$FBK_STATE"
else
    echo "No change is being made to Nighty-night mode."
fi
