name: Build Night Manager

on:
  push:
    branches:
      - packaged

permissions:
  contents: write
  packages: write
  id-token: write

env:
  GIT_USER_NAME: Night Manager Releasebot
  GIT_USER_EMAIL: actions@github.com
  
jobs:
  build:
    runs-on: ubuntu-slim
    outputs:
      artifact-path: ${{ steps.build.outputs.artifact-path }}
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup
        run: |
          curl -LO https://github.com/goreleaser/nfpm/releases/download/v2.45.0/nfpm_2.45.0_amd64.deb
          sudo dpkg -i nfpm_2.45.0_amd64.deb

      - name: Make tag_name
        id: vars
        run:  printf 'tag_name=%s.%s\n' $(date +"%Y%m%d") ${{ github.run_number }} >> $GITHUB_ENV

      - name: Build release
        id: build
        run: |
          mkdir -p build
          printf 'artifact-path=build\n' >> $GITHUB_OUTPUT
          VERSION=${{ env.tag_name }} RELEASE=1 nfpm pkg -p deb -t build

      - name: Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Night Manager Release Bot"
          git tag -a "v${TAG}" -m "Automated release v${TAG}"
          git push origin "v${TAG}"
          
      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.tag_name }}
          release_name: Release ${{ env.tag_name }}
          body: |
            Automated release ${{ env.tag_name }}
