name: Build Night Manager

on:
  push:
    branches:
      - releases

permissions:
  contents: write
  packages: write
  id-token: write

env:
  GIT_USER_NAME: Night Manager Releasebot
  GIT_USER_EMAIL: actions@github.com
  
jobs:
  build:
    runs-on: ubuntu-slim
    outputs:
      artifact-path: ${{ steps.build.outputs.artifact-path }}
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup
        run: |
          curl -LO https://github.com/goreleaser/nfpm/releases/download/v2.45.0/nfpm_2.45.0_amd64.deb
          sudo dpkg -i nfpm_2.45.0_amd64.deb

      - name: Make tag_name
        id: vars
        run: printf 'tag_name=%s.%s\n' $(date +"%Y%m%d") ${{ github.run_number }} >> $GITHUB_ENV

      - name: Build release
        id: build
        run: |
          mkdir -p build
          VERSION=${{ env.tag_name }} RELEASE=1 nfpm pkg -p deb -t build/
          cp build/*[0-9].deb build/NightManager_latest.deb
          printf 'artifact-path=build\n' >> $GITHUB_OUTPUT

      - name: Tag
        run: |
          git config --local user.email "${{ env.GIT_USER_EMAIL }}"
          git config --local user.name "${{ env.GIT_USER_NAME }}"
          git tag -a "v${{ env.tag_name }}" -m "Automated release v${{ env.tag_name }}"
          git push origin "v${{ env.tag_name }}"
          
      - name: Upload artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.tag_name }}
          name: Release ${{ env.tag_name }}
          body: |
            Automated release ${{ env.tag_name }}
          files: build/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
